# Generated by Django 4.1 on 2022-08-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pimage', models.ImageField(default='default.png', upload_to='media/')),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
    ]
