# Generated by Django 4.1 on 2022-08-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='phone', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pimage',
            field=models.ImageField(default='default.png', upload_to='uploads/'),
        ),
    ]
