# Generated by Django 4.1 on 2022-08-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_category_products_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pimage', models.ImageField(default='default.png', upload_to='cart/')),
                ('cost', models.CharField(max_length=255)),
            ],
        ),
    ]
